import type { Segment } from "../types";

const spreadsheets: Segment = {
  kind: "erp",
  slug: "spreadsheets",
  label: { en: "spreadsheet invoicing", ar: "جداول البيانات" },
  summary: {
    en: "If you invoice from Excel or by hand, this is a bigger change than the compliance work itself.",
    ar: "إن كنتم تصدرون الفواتير من Excel أو يدويًا، فهذا تغيير أكبر من عمل الامتثال نفسه.",
  },
  content: {
    en: {
      h1: "UAE e-invoicing if you invoice from spreadsheets.",
      lede: "This is the one case where the honest answer is that something does have to change. A structured e-invoice has to be generated by a system and transmitted through an accredited provider, and a spreadsheet cannot do that on its own. The real project is moving onto a connected system — which is a bigger piece of work than the compliance step, and the reason this category cannot be left late.",
      differentHeading: "What actually changes, and what does not",
      different: [
        {
          title: "Why a spreadsheet cannot be the answer",
          body: "A valid e-invoice is structured data transmitted through an accredited provider. A spreadsheet produces a document for a human to read, which is a different thing.",
        },
        {
          title: "What this actually means",
          body: "You will need an accounting system capable of producing the required data. For most businesses in this position that is a modest, well-trodden step, not an enterprise project.",
        },
        {
          title: "Why starting early matters",
          body: "Choosing a system, moving your data onto it and then implementing e-invoicing is a sequence. Compressed against a deadline, each stage gets worse.",
        },
      ],
      environmentHeading: "Common situations we see",
      environment: [
        {
          title: "Excel invoices with manual numbering",
          body: "Workable today, but there is no path from here to a valid structured invoice without a system in between.",
        },
        {
          title: "Word or PDF templates",
          body: "Same position. The document is designed for reading, not for transmission.",
        },
        {
          title: "A mix of spreadsheet and part-time accounting software",
          body: "Common, and the question becomes whether the existing software can carry the whole process.",
        },
      ],
      issuesHeading: "What tends to need resolving",
      issues: [
        {
          title: "Choosing a system without overbuying",
          body: "The goal is the smallest system that meets the requirement and suits how you actually work, not the most impressive one demonstrated to you.",
        },
        {
          title: "Moving historical data",
          body: "How much history you migrate is a decision with cost attached, and it is worth making deliberately.",
        },
        {
          title: "Customer records built from scratch",
          body: "Tax registration details for your customers will need collecting, and that takes longer than people expect.",
        },
      ],
      approachHeading: "How we work on this",
      approach: [
        "Confirm your edition, version and how invoices are actually raised today",
        "Establish your revenue tier, entities and the deadlines that follow",
        "Audit customer and item data against the fields structured invoicing requires",
        "Identify which accredited providers genuinely support your setup, and test the claim",
        "Coordinate the connection, map the data and validate against real invoices",
        "Train your team on the small number of things that change for them",
        "Stay through the first full month-end after go-live",
      ],
      note: "To be clear about what we are and are not claiming: we do not sell a pre-built spreadsheet invoicing product or plugin. We assess your setup, select and coordinate an accredited provider, and make the connection work. Where a provider advertises spreadsheet invoicing support, we test whether it fits your configuration rather than taking the claim at face value.",
      cta: "Check your readiness",
    },
    ar: {
      h1: "الفوترة الإلكترونية في الإمارات إن كنتم تصدرون الفواتير من جداول البيانات.",
      lede: "هذه هي الحالة الوحيدة التي يكون فيها الجواب الصادق أن شيئًا ما يجب أن يتغير فعلًا. فالفاتورة الإلكترونية الهيكلية يجب أن يولّدها نظام وتُرسل عبر مزوّد معتمد، وجدول البيانات وحده لا يستطيع ذلك. والمشروع الحقيقي هو الانتقال إلى نظام متصل — وهو عمل أكبر من خطوة الامتثال، وهذا سبب عدم إمكانية تأجيل هذه الفئة.",
      differentHeading: "ما الذي يتغير فعلًا، وما الذي لا يتغير",
      different: [
        {
          title: "لماذا لا يمكن أن يكون جدول البيانات هو الحل",
          body: "الفاتورة الإلكترونية الصحيحة بيانات هيكلية تُرسل عبر مزوّد معتمد. أما جدول البيانات فينتج مستندًا ليقرأه إنسان، وهذا شيء مختلف.",
        },
        {
          title: "ما يعنيه ذلك عمليًا",
          body: "ستحتاجون إلى نظام محاسبي قادر على إنتاج البيانات المطلوبة. ولمعظم من هم في هذا الوضع، تلك خطوة متواضعة ومطروقة لا مشروع مؤسسي.",
        },
        {
          title: "لماذا يهم البدء مبكرًا",
          body: "اختيار نظام ونقل بياناتكم إليه ثم تنفيذ الفوترة الإلكترونية تسلسل. وضغطه أمام موعد نهائي يجعل كل مرحلة أسوأ.",
        },
      ],
      environmentHeading: "الحالات الشائعة التي نراها",
      environment: [
        {
          title: "فواتير Excel بترقيم يدوي",
          body: "تعمل اليوم، لكن لا مسار من هنا إلى فاتورة هيكلية صحيحة دون نظام في المنتصف.",
        },
        {
          title: "قوالب Word أو PDF",
          body: "الوضع نفسه. فالمستند مصمم للقراءة لا للإرسال.",
        },
        {
          title: "مزيج من جداول البيانات وبرنامج محاسبي جزئي",
          body: "شائع، ويصبح السؤال ما إذا كان البرنامج القائم قادرًا على حمل العملية كلها.",
        },
      ],
      issuesHeading: "ما يحتاج عادةً إلى معالجة",
      issues: [
        {
          title: "اختيار نظام دون شراء زائد",
          body: "الهدف أصغر نظام يلبي المتطلب ويناسب طريقة عملكم فعلًا، لا أكثرها إبهارًا في العرض.",
        },
        {
          title: "نقل البيانات التاريخية",
          body: "حجم ما تنقلونه من تاريخ قرار له تكلفة، ويستحق أن يُتخذ عن قصد.",
        },
        {
          title: "بناء سجلات العملاء من الصفر",
          body: "ستحتاجون إلى جمع بيانات التسجيل الضريبي لعملائكم، وذلك يستغرق أطول مما يتوقع الناس.",
        },
      ],
      approachHeading: "كيف نعمل على هذا",
      approach: [
        "تأكيد نسختكم وإصداركم وكيفية إصدار الفواتير فعليًا اليوم",
        "تحديد فئة إيراداتكم وكياناتكم والمواعيد المترتبة",
        "تدقيق بيانات العملاء والأصناف مقابل الحقول التي تتطلبها الفوترة الهيكلية",
        "تحديد المزوّدين المعتمدين الذين يدعمون إعدادكم فعلًا، واختبار هذا الادعاء",
        "تنسيق الاتصال وتحويل البيانات والتحقق على فواتير واقعية",
        "تدريب فريقكم على العدد القليل من الأمور التي تتغير بالنسبة له",
        "البقاء خلال أول إقفال شهر كامل بعد الإطلاق",
      ],
      note: "توضيحًا لما ندّعيه وما لا ندّعيه: نحن لا نبيع منتجًا أو إضافة جاهزة لـ جداول البيانات. بل نقيّم إعدادكم، ونختار مزوّدًا معتمدًا وننسّق معه، ونجعل الاتصال يعمل. وحين يعلن مزوّد دعمه لـ جداول البيانات، نختبر ما إذا كان يناسب تهيئتكم بدلًا من قبول الادعاء كما هو.",
      cta: "تحقّقوا من جاهزيتكم",
    },
  },
};

export default spreadsheets;
